 export  const videoData = [
    {
        "id": 1,
        "title": "Big Buck Bunny | Demo Video 1",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://imagekit.io/player/embed/5gwch34ss/BigBuckBunny%20(1).mp4/ik-master.m3u8?controls=true&autoplay=false&loop=false&background=%23000000&thumbnail=https%3A%2F%2Fik.imagekit.io%2F5gwch34ss%2FBigBuckBunny%2520%281%29.mp4%2Fik-thumbnail.jpg%3FupdatedAt%3D1770652265815&tr=sr-240_360_480_720_1080_2160",
        "thumbnail": "https://picsum.photos/seed/video1/400/230",
        "views": "288K",
        "likes": "7K",
        "channelName": "Demo Channel 1",
        "channelAvatar": "https://i.pravatar.cc/150?img=2",
        "uploadTime": "5 days ago",
        "duration": "9:56"
    },
    {
        "id": 2,
        "title": "Elephants Dream | Demo Video 2",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://imagekit.io/player/embed/5gwch34ss/ElephantsDream%20(1).mp4/ik-master.m3u8?controls=true&autoplay=false&loop=false&background=%23000000&thumbnail=https%3A%2F%2Fik.imagekit.io%2F5gwch34ss%2FElephantsDream%2520%281%29.mp4%2Fik-thumbnail.jpg%3FupdatedAt%3D1770653671692&tr=sr-240_360_480_720_1080_2160",
        "thumbnail": "https://picsum.photos/seed/video2/400/230",
        "views": "764K",
        "likes": "33K",
        "channelName": "Demo Channel 1",
        "channelAvatar": "https://i.pravatar.cc/150?img=3",
        "uploadTime": "10 days ago",
        "duration": "10:53"
    },
    {
        "id": 3,
        "title": "Sintel | Demo Video 3",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video3/400/230",
        "views": "848K",
        "likes": "30K",
        "channelName": "Demo Channel 1",
        "channelAvatar": "https://i.pravatar.cc/150?img=4",
        "uploadTime": "6 days ago",
        "duration": "14:48"
    },
    {
        "id": 4,
        "title": "Tears of Steel | Demo Video 4",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video4/400/230",
        "views": "300K",
        "likes": "30K",
        "channelName": "Demo Channel 1",
        "channelAvatar": "https://i.pravatar.cc/150?img=5",
        "uploadTime": "10 days ago",
        "duration": "12:14"
    },
    {
        "id": 5,
        "title": "Big Buck Bunny | Demo Video 5",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video5/400/230",
        "views": "623K",
        "likes": "31K",
        "channelName": "Demo Channel 1",
        "channelAvatar": "https://i.pravatar.cc/150?img=6",
        "uploadTime": "9 days ago",
        "duration": "9:56"
    },
    {
        "id": 6,
        "title": "Elephants Dream | Demo Video 6",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video6/400/230",
        "views": "331K",
        "likes": "49K",
        "channelName": "Demo Channel 2",
        "channelAvatar": "https://i.pravatar.cc/150?img=7",
        "uploadTime": "5 days ago",
        "duration": "10:53"
    },
    {
        "id": 7,
        "title": "Sintel | Demo Video 7",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video7/400/230",
        "views": "410K",
        "likes": "42K",
        "channelName": "Demo Channel 2",
        "channelAvatar": "https://i.pravatar.cc/150?img=8",
        "uploadTime": "6 days ago",
        "duration": "14:48"
    },
    {
        "id": 8,
        "title": "Tears of Steel | Demo Video 8",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video8/400/230",
        "views": "677K",
        "likes": "13K",
        "channelName": "Demo Channel 2",
        "channelAvatar": "https://i.pravatar.cc/150?img=9",
        "uploadTime": "4 days ago",
        "duration": "12:14"
    },
    {
        "id": 9,
        "title": "Big Buck Bunny | Demo Video 9",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video9/400/230",
        "views": "878K",
        "likes": "23K",
        "channelName": "Demo Channel 2",
        "channelAvatar": "https://i.pravatar.cc/150?img=10",
        "uploadTime": "4 days ago",
        "duration": "9:56"
    },
    {
        "id": 10,
        "title": "Elephants Dream | Demo Video 10",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video10/400/230",
        "views": "945K",
        "likes": "40K",
        "channelName": "Demo Channel 2",
        "channelAvatar": "https://i.pravatar.cc/150?img=11",
        "uploadTime": "2 days ago",
        "duration": "10:53"
    },
    {
        "id": 11,
        "title": "Sintel | Demo Video 11",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video11/400/230",
        "views": "138K",
        "likes": "9K",
        "channelName": "Demo Channel 3",
        "channelAvatar": "https://i.pravatar.cc/150?img=12",
        "uploadTime": "10 days ago",
        "duration": "14:48"
    },
    {
        "id": 12,
        "title": "Tears of Steel | Demo Video 12",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video12/400/230",
        "views": "521K",
        "likes": "4K",
        "channelName": "Demo Channel 3",
        "channelAvatar": "https://i.pravatar.cc/150?img=13",
        "uploadTime": "8 days ago",
        "duration": "12:14"
    },
    {
        "id": 13,
        "title": "Big Buck Bunny | Demo Video 13",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video13/400/230",
        "views": "375K",
        "likes": "26K",
        "channelName": "Demo Channel 3",
        "channelAvatar": "https://i.pravatar.cc/150?img=14",
        "uploadTime": "4 days ago",
        "duration": "9:56"
    },
    {
        "id": 14,
        "title": "Elephants Dream | Demo Video 14",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video14/400/230",
        "views": "947K",
        "likes": "28K",
        "channelName": "Demo Channel 3",
        "channelAvatar": "https://i.pravatar.cc/150?img=15",
        "uploadTime": "3 days ago",
        "duration": "10:53"
    },
    {
        "id": 15,
        "title": "Sintel | Demo Video 15",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video15/400/230",
        "views": "529K",
        "likes": "3K",
        "channelName": "Demo Channel 3",
        "channelAvatar": "https://i.pravatar.cc/150?img=16",
        "uploadTime": "10 days ago",
        "duration": "14:48"
    },
    {
        "id": 16,
        "title": "Tears of Steel | Demo Video 16",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video16/400/230",
        "views": "161K",
        "likes": "1K",
        "channelName": "Demo Channel 4",
        "channelAvatar": "https://i.pravatar.cc/150?img=17",
        "uploadTime": "3 days ago",
        "duration": "12:14"
    },
    {
        "id": 17,
        "title": "Big Buck Bunny | Demo Video 17",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video17/400/230",
        "views": "928K",
        "likes": "26K",
        "channelName": "Demo Channel 4",
        "channelAvatar": "https://i.pravatar.cc/150?img=18",
        "uploadTime": "3 days ago",
        "duration": "9:56"
    },
    {
        "id": 18,
        "title": "Elephants Dream | Demo Video 18",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video18/400/230",
        "views": "881K",
        "likes": "50K",
        "channelName": "Demo Channel 4",
        "channelAvatar": "https://i.pravatar.cc/150?img=19",
        "uploadTime": "5 days ago",
        "duration": "10:53"
    },
    {
        "id": 19,
        "title": "Sintel | Demo Video 19",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video19/400/230",
        "views": "494K",
        "likes": "31K",
        "channelName": "Demo Channel 4",
        "channelAvatar": "https://i.pravatar.cc/150?img=20",
        "uploadTime": "2 days ago",
        "duration": "14:48"
    },
    {
        "id": 20,
        "title": "Tears of Steel | Demo Video 20",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video20/400/230",
        "views": "907K",
        "likes": "17K",
        "channelName": "Demo Channel 4",
        "channelAvatar": "https://i.pravatar.cc/150?img=21",
        "uploadTime": "4 days ago",
        "duration": "12:14"
    },
    {
        "id": 21,
        "title": "Big Buck Bunny | Demo Video 21",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video21/400/230",
        "views": "492K",
        "likes": "36K",
        "channelName": "Demo Channel 5",
        "channelAvatar": "https://i.pravatar.cc/150?img=22",
        "uploadTime": "10 days ago",
        "duration": "9:56"
    },
    {
        "id": 22,
        "title": "Elephants Dream | Demo Video 22",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video22/400/230",
        "views": "176K",
        "likes": "28K",
        "channelName": "Demo Channel 5",
        "channelAvatar": "https://i.pravatar.cc/150?img=23",
        "uploadTime": "7 days ago",
        "duration": "10:53"
    },
    {
        "id": 23,
        "title": "Sintel | Demo Video 23",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video23/400/230",
        "views": "248K",
        "likes": "25K",
        "channelName": "Demo Channel 5",
        "channelAvatar": "https://i.pravatar.cc/150?img=24",
        "uploadTime": "5 days ago",
        "duration": "14:48"
    },
    {
        "id": 24,
        "title": "Tears of Steel | Demo Video 24",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video24/400/230",
        "views": "260K",
        "likes": "4K",
        "channelName": "Demo Channel 5",
        "channelAvatar": "https://i.pravatar.cc/150?img=25",
        "uploadTime": "10 days ago",
        "duration": "12:14"
    },
    {
        "id": 25,
        "title": "Big Buck Bunny | Demo Video 25",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video25/400/230",
        "views": "404K",
        "likes": "2K",
        "channelName": "Demo Channel 5",
        "channelAvatar": "https://i.pravatar.cc/150?img=26",
        "uploadTime": "2 days ago",
        "duration": "9:56"
    },
    {
        "id": 26,
        "title": "Elephants Dream | Demo Video 26",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video26/400/230",
        "views": "388K",
        "likes": "19K",
        "channelName": "Demo Channel 6",
        "channelAvatar": "https://i.pravatar.cc/150?img=27",
        "uploadTime": "8 days ago",
        "duration": "10:53"
    },
    {
        "id": 27,
        "title": "Sintel | Demo Video 27",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video27/400/230",
        "views": "675K",
        "likes": "11K",
        "channelName": "Demo Channel 6",
        "channelAvatar": "https://i.pravatar.cc/150?img=28",
        "uploadTime": "6 days ago",
        "duration": "14:48"
    },
    {
        "id": 28,
        "title": "Tears of Steel | Demo Video 28",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video28/400/230",
        "views": "914K",
        "likes": "38K",
        "channelName": "Demo Channel 6",
        "channelAvatar": "https://i.pravatar.cc/150?img=29",
        "uploadTime": "4 days ago",
        "duration": "12:14"
    },
    {
        "id": 29,
        "title": "Big Buck Bunny | Demo Video 29",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video29/400/230",
        "views": "936K",
        "likes": "12K",
        "channelName": "Demo Channel 6",
        "channelAvatar": "https://i.pravatar.cc/150?img=30",
        "uploadTime": "9 days ago",
        "duration": "9:56"
    },
    {
        "id": 30,
        "title": "Elephants Dream | Demo Video 30",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video30/400/230",
        "views": "756K",
        "likes": "19K",
        "channelName": "Demo Channel 6",
        "channelAvatar": "https://i.pravatar.cc/150?img=31",
        "uploadTime": "2 days ago",
        "duration": "10:53"
    },
    {
        "id": 31,
        "title": "Sintel | Demo Video 31",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video31/400/230",
        "views": "590K",
        "likes": "8K",
        "channelName": "Demo Channel 7",
        "channelAvatar": "https://i.pravatar.cc/150?img=32",
        "uploadTime": "5 days ago",
        "duration": "14:48"
    },
    {
        "id": 32,
        "title": "Tears of Steel | Demo Video 32",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video32/400/230",
        "views": "480K",
        "likes": "38K",
        "channelName": "Demo Channel 7",
        "channelAvatar": "https://i.pravatar.cc/150?img=33",
        "uploadTime": "2 days ago",
        "duration": "12:14"
    },
    {
        "id": 33,
        "title": "Big Buck Bunny | Demo Video 33",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video33/400/230",
        "views": "527K",
        "likes": "31K",
        "channelName": "Demo Channel 7",
        "channelAvatar": "https://i.pravatar.cc/150?img=34",
        "uploadTime": "7 days ago",
        "duration": "9:56"
    },
    {
        "id": 34,
        "title": "Elephants Dream | Demo Video 34",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video34/400/230",
        "views": "547K",
        "likes": "34K",
        "channelName": "Demo Channel 7",
        "channelAvatar": "https://i.pravatar.cc/150?img=35",
        "uploadTime": "4 days ago",
        "duration": "10:53"
    },
    {
        "id": 35,
        "title": "Sintel | Demo Video 35",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video35/400/230",
        "views": "922K",
        "likes": "3K",
        "channelName": "Demo Channel 7",
        "channelAvatar": "https://i.pravatar.cc/150?img=36",
        "uploadTime": "2 days ago",
        "duration": "14:48"
    },
    {
        "id": 36,
        "title": "Tears of Steel | Demo Video 36",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video36/400/230",
        "views": "882K",
        "likes": "10K",
        "channelName": "Demo Channel 8",
        "channelAvatar": "https://i.pravatar.cc/150?img=37",
        "uploadTime": "8 days ago",
        "duration": "12:14"
    },
    {
        "id": 37,
        "title": "Big Buck Bunny | Demo Video 37",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video37/400/230",
        "views": "303K",
        "likes": "47K",
        "channelName": "Demo Channel 8",
        "channelAvatar": "https://i.pravatar.cc/150?img=38",
        "uploadTime": "5 days ago",
        "duration": "9:56"
    },
    {
        "id": 38,
        "title": "Elephants Dream | Demo Video 38",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video38/400/230",
        "views": "949K",
        "likes": "9K",
        "channelName": "Demo Channel 8",
        "channelAvatar": "https://i.pravatar.cc/150?img=39",
        "uploadTime": "7 days ago",
        "duration": "10:53"
    },
    {
        "id": 39,
        "title": "Sintel | Demo Video 39",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video39/400/230",
        "views": "905K",
        "likes": "15K",
        "channelName": "Demo Channel 8",
        "channelAvatar": "https://i.pravatar.cc/150?img=40",
        "uploadTime": "1 days ago",
        "duration": "14:48"
    },
    {
        "id": 40,
        "title": "Tears of Steel | Demo Video 40",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video40/400/230",
        "views": "779K",
        "likes": "36K",
        "channelName": "Demo Channel 8",
        "channelAvatar": "https://i.pravatar.cc/150?img=41",
        "uploadTime": "10 days ago",
        "duration": "12:14"
    },
    {
        "id": 41,
        "title": "Big Buck Bunny | Demo Video 41",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video41/400/230",
        "views": "984K",
        "likes": "29K",
        "channelName": "Demo Channel 9",
        "channelAvatar": "https://i.pravatar.cc/150?img=42",
        "uploadTime": "4 days ago",
        "duration": "9:56"
    },
    {
        "id": 42,
        "title": "Elephants Dream | Demo Video 42",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video42/400/230",
        "views": "376K",
        "likes": "49K",
        "channelName": "Demo Channel 9",
        "channelAvatar": "https://i.pravatar.cc/150?img=43",
        "uploadTime": "10 days ago",
        "duration": "10:53"
    },
    {
        "id": 43,
        "title": "Sintel | Demo Video 43",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video43/400/230",
        "views": "228K",
        "likes": "15K",
        "channelName": "Demo Channel 9",
        "channelAvatar": "https://i.pravatar.cc/150?img=44",
        "uploadTime": "2 days ago",
        "duration": "14:48"
    },
    {
        "id": 44,
        "title": "Tears of Steel | Demo Video 44",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video44/400/230",
        "views": "618K",
        "likes": "7K",
        "channelName": "Demo Channel 9",
        "channelAvatar": "https://i.pravatar.cc/150?img=45",
        "uploadTime": "5 days ago",
        "duration": "12:14"
    },
    {
        "id": 45,
        "title": "Big Buck Bunny | Demo Video 45",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video45/400/230",
        "views": "351K",
        "likes": "3K",
        "channelName": "Demo Channel 9",
        "channelAvatar": "https://i.pravatar.cc/150?img=46",
        "uploadTime": "5 days ago",
        "duration": "9:56"
    },
    {
        "id": 46,
        "title": "Elephants Dream | Demo Video 46",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video46/400/230",
        "views": "458K",
        "likes": "39K",
        "channelName": "Demo Channel 10",
        "channelAvatar": "https://i.pravatar.cc/150?img=47",
        "uploadTime": "5 days ago",
        "duration": "10:53"
    },
    {
        "id": 47,
        "title": "Sintel | Demo Video 47",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video47/400/230",
        "views": "640K",
        "likes": "2K",
        "channelName": "Demo Channel 10",
        "channelAvatar": "https://i.pravatar.cc/150?img=48",
        "uploadTime": "9 days ago",
        "duration": "14:48"
    },
    {
        "id": 48,
        "title": "Tears of Steel | Demo Video 48",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video48/400/230",
        "views": "423K",
        "likes": "47K",
        "channelName": "Demo Channel 10",
        "channelAvatar": "https://i.pravatar.cc/150?img=49",
        "uploadTime": "7 days ago",
        "duration": "12:14"
    },
    {
        "id": 49,
        "title": "Big Buck Bunny | Demo Video 49",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video49/400/230",
        "views": "317K",
        "likes": "5K",
        "channelName": "Demo Channel 10",
        "channelAvatar": "https://i.pravatar.cc/150?img=50",
        "uploadTime": "4 days ago",
        "duration": "9:56"
    },
    {
        "id": 50,
        "title": "Elephants Dream | Demo Video 50",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video50/400/230",
        "views": "331K",
        "likes": "43K",
        "channelName": "Demo Channel 10",
        "channelAvatar": "https://i.pravatar.cc/150?img=51",
        "uploadTime": "10 days ago",
        "duration": "10:53"
    },
    {
        "id": 51,
        "title": "Sintel | Demo Video 51",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video51/400/230",
        "views": "488K",
        "likes": "19K",
        "channelName": "Demo Channel 11",
        "channelAvatar": "https://i.pravatar.cc/150?img=52",
        "uploadTime": "8 days ago",
        "duration": "14:48"
    },
    {
        "id": 52,
        "title": "Tears of Steel | Demo Video 52",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video52/400/230",
        "views": "789K",
        "likes": "26K",
        "channelName": "Demo Channel 11",
        "channelAvatar": "https://i.pravatar.cc/150?img=53",
        "uploadTime": "4 days ago",
        "duration": "12:14"
    },
    {
        "id": 53,
        "title": "Big Buck Bunny | Demo Video 53",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video53/400/230",
        "views": "322K",
        "likes": "8K",
        "channelName": "Demo Channel 11",
        "channelAvatar": "https://i.pravatar.cc/150?img=54",
        "uploadTime": "5 days ago",
        "duration": "9:56"
    },
    {
        "id": 54,
        "title": "Elephants Dream | Demo Video 54",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video54/400/230",
        "views": "218K",
        "likes": "12K",
        "channelName": "Demo Channel 11",
        "channelAvatar": "https://i.pravatar.cc/150?img=55",
        "uploadTime": "1 days ago",
        "duration": "10:53"
    },
    {
        "id": 55,
        "title": "Sintel | Demo Video 55",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video55/400/230",
        "views": "910K",
        "likes": "25K",
        "channelName": "Demo Channel 11",
        "channelAvatar": "https://i.pravatar.cc/150?img=56",
        "uploadTime": "3 days ago",
        "duration": "14:48"
    },
    {
        "id": 56,
        "title": "Tears of Steel | Demo Video 56",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video56/400/230",
        "views": "634K",
        "likes": "23K",
        "channelName": "Demo Channel 12",
        "channelAvatar": "https://i.pravatar.cc/150?img=57",
        "uploadTime": "3 days ago",
        "duration": "12:14"
    },
    {
        "id": 57,
        "title": "Big Buck Bunny | Demo Video 57",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video57/400/230",
        "views": "606K",
        "likes": "6K",
        "channelName": "Demo Channel 12",
        "channelAvatar": "https://i.pravatar.cc/150?img=58",
        "uploadTime": "5 days ago",
        "duration": "9:56"
    },
    {
        "id": 58,
        "title": "Elephants Dream | Demo Video 58",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video58/400/230",
        "views": "566K",
        "likes": "40K",
        "channelName": "Demo Channel 12",
        "channelAvatar": "https://i.pravatar.cc/150?img=59",
        "uploadTime": "3 days ago",
        "duration": "10:53"
    },
    {
        "id": 59,
        "title": "Sintel | Demo Video 59",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video59/400/230",
        "views": "285K",
        "likes": "42K",
        "channelName": "Demo Channel 12",
        "channelAvatar": "https://i.pravatar.cc/150?img=60",
        "uploadTime": "6 days ago",
        "duration": "14:48"
    },
    {
        "id": 60,
        "title": "Tears of Steel | Demo Video 60",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video60/400/230",
        "views": "754K",
        "likes": "23K",
        "channelName": "Demo Channel 12",
        "channelAvatar": "https://i.pravatar.cc/150?img=61",
        "uploadTime": "7 days ago",
        "duration": "12:14"
    },
    {
        "id": 61,
        "title": "Big Buck Bunny | Demo Video 61",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video61/400/230",
        "views": "466K",
        "likes": "4K",
        "channelName": "Demo Channel 13",
        "channelAvatar": "https://i.pravatar.cc/150?img=62",
        "uploadTime": "2 days ago",
        "duration": "9:56"
    },
    {
        "id": 62,
        "title": "Elephants Dream | Demo Video 62",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video62/400/230",
        "views": "968K",
        "likes": "35K",
        "channelName": "Demo Channel 13",
        "channelAvatar": "https://i.pravatar.cc/150?img=63",
        "uploadTime": "1 days ago",
        "duration": "10:53"
    },
    {
        "id": 63,
        "title": "Sintel | Demo Video 63",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video63/400/230",
        "views": "362K",
        "likes": "1K",
        "channelName": "Demo Channel 13",
        "channelAvatar": "https://i.pravatar.cc/150?img=64",
        "uploadTime": "2 days ago",
        "duration": "14:48"
    },
    {
        "id": 64,
        "title": "Tears of Steel | Demo Video 64",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video64/400/230",
        "views": "487K",
        "likes": "20K",
        "channelName": "Demo Channel 13",
        "channelAvatar": "https://i.pravatar.cc/150?img=65",
        "uploadTime": "10 days ago",
        "duration": "12:14"
    },
    {
        "id": 65,
        "title": "Big Buck Bunny | Demo Video 65",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video65/400/230",
        "views": "107K",
        "likes": "20K",
        "channelName": "Demo Channel 13",
        "channelAvatar": "https://i.pravatar.cc/150?img=66",
        "uploadTime": "3 days ago",
        "duration": "9:56"
    },
    {
        "id": 66,
        "title": "Elephants Dream | Demo Video 66",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video66/400/230",
        "views": "351K",
        "likes": "19K",
        "channelName": "Demo Channel 14",
        "channelAvatar": "https://i.pravatar.cc/150?img=67",
        "uploadTime": "8 days ago",
        "duration": "10:53"
    },
    {
        "id": 67,
        "title": "Sintel | Demo Video 67",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video67/400/230",
        "views": "721K",
        "likes": "16K",
        "channelName": "Demo Channel 14",
        "channelAvatar": "https://i.pravatar.cc/150?img=68",
        "uploadTime": "10 days ago",
        "duration": "14:48"
    },
    {
        "id": 68,
        "title": "Tears of Steel | Demo Video 68",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video68/400/230",
        "views": "965K",
        "likes": "7K",
        "channelName": "Demo Channel 14",
        "channelAvatar": "https://i.pravatar.cc/150?img=69",
        "uploadTime": "6 days ago",
        "duration": "12:14"
    },
    {
        "id": 69,
        "title": "Big Buck Bunny | Demo Video 69",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video69/400/230",
        "views": "656K",
        "likes": "39K",
        "channelName": "Demo Channel 14",
        "channelAvatar": "https://i.pravatar.cc/150?img=70",
        "uploadTime": "7 days ago",
        "duration": "9:56"
    },
    {
        "id": 70,
        "title": "Elephants Dream | Demo Video 70",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video70/400/230",
        "views": "461K",
        "likes": "43K",
        "channelName": "Demo Channel 14",
        "channelAvatar": "https://i.pravatar.cc/150?img=1",
        "uploadTime": "9 days ago",
        "duration": "10:53"
    },
    {
        "id": 71,
        "title": "Sintel | Demo Video 71",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video71/400/230",
        "views": "622K",
        "likes": "29K",
        "channelName": "Demo Channel 15",
        "channelAvatar": "https://i.pravatar.cc/150?img=2",
        "uploadTime": "8 days ago",
        "duration": "14:48"
    },
    {
        "id": 72,
        "title": "Tears of Steel | Demo Video 72",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video72/400/230",
        "views": "662K",
        "likes": "27K",
        "channelName": "Demo Channel 15",
        "channelAvatar": "https://i.pravatar.cc/150?img=3",
        "uploadTime": "8 days ago",
        "duration": "12:14"
    },
    {
        "id": 73,
        "title": "Big Buck Bunny | Demo Video 73",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video73/400/230",
        "views": "931K",
        "likes": "8K",
        "channelName": "Demo Channel 15",
        "channelAvatar": "https://i.pravatar.cc/150?img=4",
        "uploadTime": "6 days ago",
        "duration": "9:56"
    },
    {
        "id": 74,
        "title": "Elephants Dream | Demo Video 74",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video74/400/230",
        "views": "277K",
        "likes": "20K",
        "channelName": "Demo Channel 15",
        "channelAvatar": "https://i.pravatar.cc/150?img=5",
        "uploadTime": "2 days ago",
        "duration": "10:53"
    },
    {
        "id": 75,
        "title": "Sintel | Demo Video 75",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video75/400/230",
        "views": "353K",
        "likes": "1K",
        "channelName": "Demo Channel 15",
        "channelAvatar": "https://i.pravatar.cc/150?img=6",
        "uploadTime": "1 days ago",
        "duration": "14:48"
    },
    {
        "id": 76,
        "title": "Tears of Steel | Demo Video 76",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video76/400/230",
        "views": "995K",
        "likes": "40K",
        "channelName": "Demo Channel 16",
        "channelAvatar": "https://i.pravatar.cc/150?img=7",
        "uploadTime": "4 days ago",
        "duration": "12:14"
    },
    {
        "id": 77,
        "title": "Big Buck Bunny | Demo Video 77",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video77/400/230",
        "views": "441K",
        "likes": "16K",
        "channelName": "Demo Channel 16",
        "channelAvatar": "https://i.pravatar.cc/150?img=8",
        "uploadTime": "2 days ago",
        "duration": "9:56"
    },
    {
        "id": 78,
        "title": "Elephants Dream | Demo Video 78",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video78/400/230",
        "views": "381K",
        "likes": "12K",
        "channelName": "Demo Channel 16",
        "channelAvatar": "https://i.pravatar.cc/150?img=9",
        "uploadTime": "9 days ago",
        "duration": "10:53"
    },
    {
        "id": 79,
        "title": "Sintel | Demo Video 79",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video79/400/230",
        "views": "669K",
        "likes": "13K",
        "channelName": "Demo Channel 16",
        "channelAvatar": "https://i.pravatar.cc/150?img=10",
        "uploadTime": "8 days ago",
        "duration": "14:48"
    },
    {
        "id": 80,
        "title": "Tears of Steel | Demo Video 80",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video80/400/230",
        "views": "671K",
        "likes": "11K",
        "channelName": "Demo Channel 16",
        "channelAvatar": "https://i.pravatar.cc/150?img=11",
        "uploadTime": "5 days ago",
        "duration": "12:14"
    },
    {
        "id": 81,
        "title": "Big Buck Bunny | Demo Video 81",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video81/400/230",
        "views": "193K",
        "likes": "12K",
        "channelName": "Demo Channel 17",
        "channelAvatar": "https://i.pravatar.cc/150?img=12",
        "uploadTime": "5 days ago",
        "duration": "9:56"
    },
    {
        "id": 82,
        "title": "Elephants Dream | Demo Video 82",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video82/400/230",
        "views": "957K",
        "likes": "42K",
        "channelName": "Demo Channel 17",
        "channelAvatar": "https://i.pravatar.cc/150?img=13",
        "uploadTime": "6 days ago",
        "duration": "10:53"
    },
    {
        "id": 83,
        "title": "Sintel | Demo Video 83",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video83/400/230",
        "views": "225K",
        "likes": "39K",
        "channelName": "Demo Channel 17",
        "channelAvatar": "https://i.pravatar.cc/150?img=14",
        "uploadTime": "2 days ago",
        "duration": "14:48"
    },
    {
        "id": 84,
        "title": "Tears of Steel | Demo Video 84",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video84/400/230",
        "views": "906K",
        "likes": "46K",
        "channelName": "Demo Channel 17",
        "channelAvatar": "https://i.pravatar.cc/150?img=15",
        "uploadTime": "7 days ago",
        "duration": "12:14"
    },
    {
        "id": 85,
        "title": "Big Buck Bunny | Demo Video 85",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video85/400/230",
        "views": "545K",
        "likes": "14K",
        "channelName": "Demo Channel 17",
        "channelAvatar": "https://i.pravatar.cc/150?img=16",
        "uploadTime": "10 days ago",
        "duration": "9:56"
    },
    {
        "id": 86,
        "title": "Elephants Dream | Demo Video 86",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video86/400/230",
        "views": "383K",
        "likes": "5K",
        "channelName": "Demo Channel 18",
        "channelAvatar": "https://i.pravatar.cc/150?img=17",
        "uploadTime": "8 days ago",
        "duration": "10:53"
    },
    {
        "id": 87,
        "title": "Sintel | Demo Video 87",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video87/400/230",
        "views": "101K",
        "likes": "21K",
        "channelName": "Demo Channel 18",
        "channelAvatar": "https://i.pravatar.cc/150?img=18",
        "uploadTime": "9 days ago",
        "duration": "14:48"
    },
    {
        "id": 88,
        "title": "Tears of Steel | Demo Video 88",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video88/400/230",
        "views": "848K",
        "likes": "43K",
        "channelName": "Demo Channel 18",
        "channelAvatar": "https://i.pravatar.cc/150?img=19",
        "uploadTime": "7 days ago",
        "duration": "12:14"
    },
    {
        "id": 89,
        "title": "Big Buck Bunny | Demo Video 89",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video89/400/230",
        "views": "246K",
        "likes": "21K",
        "channelName": "Demo Channel 18",
        "channelAvatar": "https://i.pravatar.cc/150?img=20",
        "uploadTime": "7 days ago",
        "duration": "9:56"
    },
    {
        "id": 90,
        "title": "Elephants Dream | Demo Video 90",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video90/400/230",
        "views": "216K",
        "likes": "34K",
        "channelName": "Demo Channel 18",
        "channelAvatar": "https://i.pravatar.cc/150?img=21",
        "uploadTime": "10 days ago",
        "duration": "10:53"
    },
    {
        "id": 91,
        "title": "Sintel | Demo Video 91",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video91/400/230",
        "views": "929K",
        "likes": "35K",
        "channelName": "Demo Channel 19",
        "channelAvatar": "https://i.pravatar.cc/150?img=22",
        "uploadTime": "5 days ago",
        "duration": "14:48"
    },
    {
        "id": 92,
        "title": "Tears of Steel | Demo Video 92",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video92/400/230",
        "views": "812K",
        "likes": "40K",
        "channelName": "Demo Channel 19",
        "channelAvatar": "https://i.pravatar.cc/150?img=23",
        "uploadTime": "5 days ago",
        "duration": "12:14"
    },
    {
        "id": 93,
        "title": "Big Buck Bunny | Demo Video 93",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video93/400/230",
        "views": "748K",
        "likes": "2K",
        "channelName": "Demo Channel 19",
        "channelAvatar": "https://i.pravatar.cc/150?img=24",
        "uploadTime": "7 days ago",
        "duration": "9:56"
    },
    {
        "id": 94,
        "title": "Elephants Dream | Demo Video 94",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video94/400/230",
        "views": "393K",
        "likes": "3K",
        "channelName": "Demo Channel 19",
        "channelAvatar": "https://i.pravatar.cc/150?img=25",
        "uploadTime": "3 days ago",
        "duration": "10:53"
    },
    {
        "id": 95,
        "title": "Sintel | Demo Video 95",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video95/400/230",
        "views": "965K",
        "likes": "10K",
        "channelName": "Demo Channel 19",
        "channelAvatar": "https://i.pravatar.cc/150?img=26",
        "uploadTime": "2 days ago",
        "duration": "14:48"
    },
    {
        "id": 96,
        "title": "Tears of Steel | Demo Video 96",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video96/400/230",
        "views": "717K",
        "likes": "39K",
        "channelName": "Demo Channel 20",
        "channelAvatar": "https://i.pravatar.cc/150?img=27",
        "uploadTime": "3 days ago",
        "duration": "12:14"
    },
    {
        "id": 97,
        "title": "Big Buck Bunny | Demo Video 97",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        "thumbnail": "https://picsum.photos/seed/video97/400/230",
        "views": "788K",
        "likes": "31K",
        "channelName": "Demo Channel 20",
        "channelAvatar": "https://i.pravatar.cc/150?img=28",
        "uploadTime": "6 days ago",
        "duration": "9:56"
    },
    {
        "id": 98,
        "title": "Elephants Dream | Demo Video 98",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        "thumbnail": "https://picsum.photos/seed/video98/400/230",
        "views": "594K",
        "likes": "19K",
        "channelName": "Demo Channel 20",
        "channelAvatar": "https://i.pravatar.cc/150?img=29",
        "uploadTime": "7 days ago",
        "duration": "10:53"
    },
    {
        "id": 99,
        "title": "Sintel | Demo Video 99",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        "thumbnail": "https://picsum.photos/seed/video99/400/230",
        "views": "767K",
        "likes": "5K",
        "channelName": "Demo Channel 20",
        "channelAvatar": "https://i.pravatar.cc/150?img=30",
        "uploadTime": "4 days ago",
        "duration": "14:48"
    },
    {
        "id": 100,
        "title": "Tears of Steel | Demo Video 100",
        "description": "Demo video for YouTube clone project.",
        "videoUrl": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        "thumbnail": "https://picsum.photos/seed/video100/400/230",
        "views": "530K",
        "likes": "44K",
        "channelName": "Demo Channel 20",
        "channelAvatar": "https://i.pravatar.cc/150?img=31",
        "uploadTime": "3 days ago",
        "duration": "12:14"
    }
]